begin;
select plan(17);
select has_function('public','assert_crm_analytics_range',ARRAY['timestamp with time zone','timestamp with time zone'],'range guard exists');
select has_function('public','crm_analytics_overview',ARRAY['timestamp with time zone','timestamp with time zone','timestamp with time zone','timestamp with time zone'],'overview report exists');
select has_function('public','crm_analytics_acquisition',ARRAY['timestamp with time zone','timestamp with time zone'],'acquisition report exists');
select has_function('public','crm_analytics_leads',ARRAY['timestamp with time zone','timestamp with time zone'],'lead report exists');
select has_function('public','crm_analytics_pipeline',ARRAY['timestamp with time zone','timestamp with time zone'],'pipeline report exists');
select has_function('public','crm_analytics_operations',ARRAY['timestamp with time zone','timestamp with time zone'],'operations report exists');
select ok(has_function_privilege('authenticated','public.crm_analytics_overview(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone)','EXECUTE'),'authenticated may execute overview through RLS');
select ok(not has_function_privilege('anon','public.crm_analytics_overview(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone)','EXECUTE'),'anon cannot execute overview');
select ok(not has_function_privilege('anon','public.crm_analytics_acquisition(timestamp with time zone,timestamp with time zone)','EXECUTE'),'anon cannot execute acquisition');
select ok(not has_function_privilege('anon','public.crm_analytics_leads(timestamp with time zone,timestamp with time zone)','EXECUTE'),'anon cannot execute leads');
select ok(not has_function_privilege('anon','public.crm_analytics_pipeline(timestamp with time zone,timestamp with time zone)','EXECUTE'),'anon cannot execute pipeline');
select ok(not has_function_privilege('anon','public.crm_analytics_operations(timestamp with time zone,timestamp with time zone)','EXECUTE'),'anon cannot execute operations');
select is((select prosecdef from pg_proc where oid='public.crm_analytics_overview(timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone)'::regprocedure),false,'overview uses invoker rights');
select ok((select count(*) from pg_indexes where indexname='sessions_started_visitor_reporting_idx')=1,'session reporting index exists');
select ok((select count(*) from pg_indexes where indexname='people_created_canonical_reporting_idx')=1,'canonical people reporting index exists');
select ok((select count(*) from pg_indexes where indexname='opportunity_history_changed_stage_reporting_idx')=1,'stage transition reporting index exists');
select throws_ok($$select public.assert_crm_analytics_range('2020-01-01'::timestamptz,'2025-01-01'::timestamptz)$$,'42501','active staff authorization is required','range guard rejects unauthenticated callers before query validation');
select * from finish();
rollback;
