begin;
select plan(34);
select has_table('public','automation_policy_versions','versioned automation policy exists');
select has_table('public','automation_policy_decisions','policy decision history exists');
select has_table('public','automation_approvals','approval history exists');
select has_table('public','automation_job_events','job event history exists');
select has_view('public','crm_automation_jobs_projection','bounded automation job projection exists');
select has_view('public','crm_automation_agents_projection','safe agent projection exists');
select has_column('public','automation_jobs','communication_purpose','jobs require communication purpose contract');
select has_column('public','automation_jobs','policy_version_id','jobs retain policy version');
select has_column('public','automation_jobs','payload_hash','jobs retain payload integrity hash');
select has_column('public','automation_jobs','version','jobs support optimistic concurrency');
select has_column('public','automation_jobs','dry_run','jobs record dry-run semantics');
select has_column('public','automation_agents','capabilities','agents expose safe capabilities');
select has_column('public','automation_actions','execution_key','attempts expose an execution idempotency reference');
select has_function('public','activate_automation_policy',array['jsonb','text'],'owner policy activation RPC exists');
select has_function('public','automation_check_job',array['uuid','text','timestamp with time zone'],'policy recheck RPC exists');
select has_function('public','propose_automation_job',array['uuid','uuid','text','text','text','jsonb','text','text','timestamp with time zone','integer'],'proposal RPC exists');
select has_function('public','approve_automation_job',array['uuid','integer'],'approval RPC exists');
select has_function('public','reject_automation_job',array['uuid','integer','text'],'rejection RPC exists');
select has_function('public','cancel_automation_job',array['uuid','integer','text'],'cancellation RPC exists');
select has_function('public','start_automation_job',array['uuid','uuid'],'start RPC exists');
select has_function('public','complete_automation_job',array['uuid','uuid','jsonb'],'completion RPC exists');
select has_function('public','fail_automation_job',array['uuid','uuid','text','text','timestamp with time zone'],'failure RPC exists');
select has_function('public','recover_expired_automation_jobs',array['timestamp with time zone'],'lease recovery RPC exists');
select has_function('public','record_automation_heartbeat',array['uuid','text','jsonb','jsonb'],'server-only heartbeat boundary exists');
select has_function('public','resolve_automation_manual_action',array['uuid','integer','text','text'],'manual resolution RPC exists');
select ok((select relrowsecurity from pg_class where oid='public.automation_policy_versions'::regclass),'policy versions keep RLS');
select ok((select relrowsecurity from pg_class where oid='public.automation_policy_decisions'::regclass),'decisions keep RLS');
select ok((select relrowsecurity from pg_class where oid='public.automation_approvals'::regclass),'approvals keep RLS');
select ok((select relrowsecurity from pg_class where oid='public.automation_job_events'::regclass),'events keep RLS');
select is((select count(*)::integer from public.automation_policy_versions where active),1,'one active policy is seeded');
select is((select configuration->>'enabled' from public.automation_policy_versions where active),'false','default automation is disabled');
select is((select configuration->>'dryRun' from public.automation_policy_versions where active),'true','default is dry-run');
select is((select configuration->>'approvalRequired' from public.automation_policy_versions where active),'true','default requires approval');
select ok(not has_table_privilege('authenticated','public.automation_jobs','UPDATE'),'browser cannot mutate queue state directly');
select * from finish();
rollback;
