begin;
select plan(18);
select has_table('public','lead_scoring_models','versioned scoring model table exists');
select has_column('public','opportunities','version','opportunity optimistic version exists');
select has_column('public','tasks','version','task optimistic version exists');
select has_view('public','crm_current_lead_score','current score view exists');
select has_view('public','crm_pipeline_projection','pipeline projection exists');
select has_view('public','crm_task_projection','task projection exists');
select has_function('public','get_active_lead_scoring_model',ARRAY[]::text[],'active model function exists');
select has_function('public','persist_lead_score',ARRAY['uuid','integer','text','jsonb','jsonb','text','timestamp with time zone'],'score persistence boundary exists');
select has_function('public','transition_opportunity_stage',ARRAY['uuid','uuid','timestamp with time zone','text','text'],'stage transition function exists');
select has_function('public','update_opportunity',ARRAY['uuid','timestamp with time zone','text','numeric','text','numeric','jsonb','uuid','date'],'opportunity update function exists');
select has_function('public','create_crm_task',ARRAY['uuid','uuid','uuid','text','text','timestamp with time zone','text'],'task creation function exists');
select has_function('public','update_crm_task',ARRAY['uuid','timestamp with time zone','uuid','text','text','timestamp with time zone','text','text'],'task update function exists');
select ok((select relrowsecurity from pg_class where oid='public.lead_scoring_models'::regclass),'scoring models keep RLS enabled');
select is((select count(*)::integer from public.lead_scoring_models where active),1,'exactly one active scoring model');
select is((select model_key||'_V'||version from public.lead_scoring_models where active),'ZAVLIO_LEAD_V1','active model version is stable');
select ok((select count(*) from pg_indexes where indexname='lead_scoring_models_one_active_idx')=1,'one-active-model index exists');
select ok(not has_table_privilege('authenticated','public.lead_scores','INSERT'),'authenticated cannot forge score history');
select ok(not has_table_privilege('authenticated','public.tasks','DELETE'),'tasks cannot be hard deleted by staff');
select * from finish();
rollback;
