import { parsePublicEnv } from '@zavlio/validation/env';

export const publicEnv = parsePublicEnv({
  NEXT_PUBLIC_ANALYTICS_DEBUG: process.env.NEXT_PUBLIC_ANALYTICS_DEBUG,
  NEXT_PUBLIC_ANALYTICS_ENABLED: process.env.NEXT_PUBLIC_ANALYTICS_ENABLED ?? 'true',
  NEXT_PUBLIC_ANALYTICS_POLICY_VERSION: process.env.NEXT_PUBLIC_ANALYTICS_POLICY_VERSION,
  NEXT_PUBLIC_ENABLE_PORTAL: process.env.NEXT_PUBLIC_ENABLE_PORTAL,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
});
