-- Zavlio Packet 06 / 08: indexes for expected relational access paths.
create index organizations_domain_idx on public.organizations (domain) where domain is not null;
create index people_lifecycle_stage_idx on public.people (lifecycle_stage);
create index people_owner_idx on public.people (owner_id) where owner_id is not null;
create index people_last_activity_idx on public.people (last_activity_at desc nulls last);
create index anonymous_visitors_linked_person_idx on public.anonymous_visitors (linked_person_id) where linked_person_id is not null;
create index sessions_visitor_started_idx on public.sessions (visitor_id, started_at desc);
create index sessions_person_started_idx on public.sessions (person_id, started_at desc) where person_id is not null;
create index sessions_utm_source_idx on public.sessions (utm_source) where utm_source is not null;
create index identities_provider_username_idx on public.identities (provider, username) where username is not null;
create index identity_candidates_status_idx on public.identity_match_candidates (status, confidence desc);
create index consents_person_captured_idx on public.consents (person_id, captured_at desc) where person_id is not null;
create index consents_visitor_captured_idx on public.consents (visitor_id, captured_at desc) where visitor_id is not null;
create index events_visitor_occurred_idx on public.events (visitor_id, occurred_at desc) where visitor_id is not null;
create index events_person_occurred_idx on public.events (person_id, occurred_at desc) where person_id is not null;
create index events_session_occurred_idx on public.events (session_id, occurred_at desc) where session_id is not null;
create index events_name_occurred_idx on public.events (event_name, occurred_at desc);
create index lead_scores_person_calculated_idx on public.lead_scores (person_id, calculated_at desc);
create index opportunities_stage_idx on public.opportunities (stage_id);
create index opportunities_owner_idx on public.opportunities (owner_id) where owner_id is not null;
create index opportunity_history_opportunity_changed_idx on public.opportunity_stage_history (opportunity_id, changed_at desc);
create index tasks_assigned_status_due_idx on public.tasks (assigned_to, status, due_at) where assigned_to is not null;
create index tasks_opportunity_idx on public.tasks (opportunity_id) where opportunity_id is not null;
create index notes_person_created_idx on public.notes (person_id, created_at desc) where person_id is not null;
create index touchpoints_person_occurred_idx on public.touchpoints (person_id, occurred_at desc);
create index conversations_person_channel_idx on public.conversations (person_id, channel);
create index messages_conversation_created_idx on public.messages (conversation_id, created_at desc);
create index campaigns_status_idx on public.campaigns (status);
create index automation_jobs_status_scheduled_idx on public.automation_jobs (status, scheduled_for, priority desc);
create index automation_jobs_claimed_idx on public.automation_jobs (claimed_by, lease_expires_at) where claimed_by is not null;
create index automation_runs_agent_started_idx on public.automation_runs (agent_id, started_at desc);
create index automation_actions_job_idx on public.automation_actions (automation_job_id, requested_at desc);
create index automation_nonces_expires_idx on public.automation_nonces (expires_at);
create index audit_entity_created_idx on public.audit_logs (entity_type, entity_id, created_at desc);
create index audit_actor_created_idx on public.audit_logs (actor_id, created_at desc) where actor_id is not null;
